import React from "react";

function SummaryBox({ bullets = [] }) {
  return (
    <div className="relative mb-10">
      {/* Gradient border */}
      <div className="absolute -inset-[1px] bg-gradient-to-r from-yellow-400/40 via-cyan-400/30 to-violet-400/40 rounded-xl blur-sm opacity-60"></div>

      <div className="relative bg-slate-900/80 border border-white/10 rounded-xl p-6 backdrop-blur">
        {/* Header */}
        <div className="flex items-center gap-3 mb-5">
          <div className="w-9 h-9 flex items-center justify-center rounded-lg bg-yellow-400/10 text-yellow-300 text-lg">
            🤖
          </div>

          <div>
            <h2 className="text-lg font-semibold text-paper">AI Summary</h2>
            <p className="text-xs text-paper/40">
              Quick overview generated by AI
            </p>
          </div>
        </div>

        {/* Bullet Points */}
        <ul className="space-y-3">
          {bullets.length > 0 ? (
            bullets.map((point, index) => (
              <li
                key={index}
                className="flex gap-3 text-paper/80 leading-relaxed"
              >
                <span className="text-yellow-400 mt-1">•</span>
                <span>{point.trim()}</span>
              </li>
            ))
          ) : (
            <li className="text-paper/40 text-sm">No summary available.</li>
          )}
        </ul>
      </div>
    </div>
  );
}

export default SummaryBox;
